### ISSUE TITLE
Detekcija i klasifikacija ljudskih akcija

### ISSUE THREAD

**Issue by StjepanovicSrdjan** [ftn-ai-lab/sc-2023#1]
**Tim:**
Srđan Stjepanović, SV16/2020

**Asistent:**
Vidaković Dragan

**Definicija problema:**
Detekcija čovjeka na slici i klasifikacija njegove trenutne aktivnosti na osnovu njegove poze

**Skup podataka:**
Skup podataka sa slikama ljudi i labelama njihove aktivnosti
https://www.kaggle.com/datasets/meetnagadia/human-action-recognition-har-dataset

**Metodologija:**
Skup podataka će se pretprocesirati koristeći OpenPose model za izdvajanje ključnih tačaka ljudskog tijela što će biti ulaz u različite modele za klasifikaciju (Neural network, SVM, random forest), čiji rezultati će se porediti.

**Evaluacija:**
Accuracy, precision

**Comment by vdragan1993** [comment]
U definiciju problema je potrebno dodati skup svih aktivnosti za klasifikaciju.
U evaluaciju je potrebno dodati opis eksperimentalne postavke.

**Comment by StjepanovicSrdjan** [comment]
Prethodno navedeni skup podataka sadrži 15 različitih ljudskih aktivnosti: hugging, fighting, laughing, sleeping, using laptop, cycling, calling, drinking, clapping, eating, sitting, dancing, listening to music, texting, running. Skup podataka je sačinjen od 12000 slika koje će biti podijeljene na trening i test podatke u odnosu 80:20.
Evaluacija klasifikacije će se vršiti koristeći accuracy i precision metrike.

**Comment by vdragan1993** [comment]
Pošto je u pitanju klasifikacija u više klasa, za evaluaciju klasifikacije je neophodno računati i recall i f1 meru.

Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by StjepanovicSrdjan** [comment]
https://github.com/StjepanovicSrdjan/Human-Action-Recognition
