### ISSUE TITLE
Upravljanje kalkulatorom pomoću govora i gestikulacije šake

### ISSUE THREAD

**Issue by slepimis120** [ftn-ai-lab/sc-2023#10]
### Tim:
Katarina Vučić SV29/2020

Hristina Adamović SV32/2020

Nemanja Šimšić SV68/2020
***
### Asistent:
Njegomir Marko
***
### Definicija problema:
Implementacija kalkulatora koristeći zvuk i video kao ulaz. Podržane operacije su sabiranje, oduzimanje, množenje i deljenje.
***
### Skup podataka:
Skup podataka će biti generisan ručno, od strane članova tima.

Tačne vrednosti za testiranje i treniranje će se skladištiti u CSV fajlu.
***
### Metodologija:
Za klasifikaciju gesture ruke će biti korišćen CNN model, dok će za klasifikaciju zvuka biti korišćen MFCC model, zajedno sa SVM klasifikatorom.

Na kraju će se vršiti izračunavanje svih dobijenih izlaza i dobijeni rezultat će biti poređen
sa očekivanim.
***
### Evaluacija:
Za treniranje će biti iskorišteno 80% podataka, dok će za testiranje 20%.

Za evaluaciju kalkulatora će se koristiti metrika tačnosti.

Za evaluaciju klasifikacije će se koristiti sledeće metrike:
- preciznost
- tačnost
- odziv
- F mera
***
### GitHub repozitorijum:
https://github.com/slepimis120/Sakalkulator/

**Comment by njmarko** [comment]
У евалуацију је потребно додати опис експерименталне поставке.
Ако YOLO користите само за детекцију bounding box-a руке, онда она треба додати IoU меру перформансе за тај део.

**Comment by slepimis120** [comment]
Update-ovana specifikacija!
Odlučili smo se da ipak ne radimo real-time procesiranje videa, već ćemo raditi obradu već ranije predefinisanih videa, samim time ne koristimo više YOLO algoritam.

**Comment by njmarko** [comment]
Пројекат одобрен.
Срећан рад!
