### ISSUE TITLE
Image Style Transfer

### ISSUE THREAD

**Issue by vujadinovicn** [ftn-ai-lab/sc-2023#13]
### Tim:
Nemanja Vujadinović
### Asistent: 
Marko Njegomir 
### Definicija problema:
Image Style Transfer predstavlja tehniku u oblasti _computer vision-a_ čija ideja je da za dve slike - _content_ i _style_ _image_, generiše novu tako što će generisana slika sad predstavljati spoj dve ulazne - jednostavnije rečeno, sadržaj prve slike, biće 'naslikan' u stilu druge. Osnovni primer ove tehnike bio bi da se nečiji portret ili pejzaž, pretvori u onakav kakvog bi Pablo Picasso ili neko od drugih velikih umetnika, stvorio.
U ovom projektu, baziraćemo se na _Neural Style Transfer-u_ i generisanju pomoću _Generative Adversarial Networks_. (NST će svakako biti implementiran, a ukoliko vreme dozvoli i rešenje pomoću GAN-ova, pa će biti moguće porediti rezultate.)

### Metodologija:
Za implementaciju _NST-a_, koristiće se tehnika _Transfer learning-a_ sa _pretrained VGG-19_ mrežom.
Za generisanje slika pomoću _GAN-ova_, koristiće se _CycleGAN_.

### Skup podataka:

- U slučaju NST-a, sam _training_ i _training set_ neće postojati, pa će u _inference-u_ biti moguće koristiti podatke (dve slike) po želji. Za _style image_, između ostalih, mogu biti korisne i slike iz skupa podataka za _CycleGAN_ implementaciju.
- U slučaju CycleGAN-a, za _style images_ biće korišten _WikiArt_ skup podataka koji sadrži stilove i radove više od 150 umetnika. Za slike pejzaža, koristan skup podataka je _Flickr_, a za portrete _CelebA_ ili neki sličan skup koji izoluje portrete osoba.

### Evaluacija
Empirijski će se porediti rezultati ova dva pristupa, što će se najviše bazirati na samom izgledu generisanih slika. Takođe porediće se i same performanse. (U slučaju implementacije isključivo NST-a, rezultati će se empirijski evaluirati.)

**Comment by njmarko** [comment]
Тема одобрена.
Потребно је да оставиш линк ка Github репозиторијуму.
Срећан рад!

**Comment by vujadinovicn** [comment]
Link: https://github.com/vujadinovicn/image-style-transfer
