### ISSUE TITLE
Fino podešavanje diffusion modela

### ISSUE THREAD

**Issue by tince250** [ftn-ai-lab/sc-2023#14]
## Tim:
- Tina Mihajlović SV3/2020

## Asistent:
- Marko Njegomir

## Motivacija:
Diffusion modeli su trenutni state-of-the-art pristup za generisanje fotografija u svetu veštačke inteligencije - na osnovu tekstualnog opisa, ovi modeli generišu slike koje odgovaraju tom opisu (text to image).

Stable Diffusion je open source latentni diffusion model koji postiže zavidne rezultate na zadatku generalne generacije slika, međutim, njegova prava moć leži u velikom broju metoda za dotreniravanje baznih modela za generaciju specifičnih stilova, karaktera i kompozicija.

## Definicija problema:
Cilj projekta je istraživanje arhitekture diffusion modela, primena Stable Diffusion-a kroz Automatic1111 open source ui, kao i dotreniravanje modela ubacivanjem novog koncepta koji bi on nakon toga verno reprodukovao.

## Metodologija:
Postoji više načina za fino podešavanje Stable Diffusion modela (DreamBooth, LoRA, ControlNet, textual inversion...).
Za ovaj projekat fokus će biti na finom podešavanju koristeći LoRA-e (Low Rank Adaptation Matrices), pristup u kom se naučene težine modela zamrznu, a u attention slojeve se "injektuju" matrice koje čuvaju razliku originalnih i dotreniravanjem naučenih težina tih attention slojeva - cilj dotreniravanja je upravo ucenje težina tih injektovanih matrica.

LoRA pristup daje sjajne rezultate u zadacima kao što su: generacija slika u odredjenom stilu (Disney stil), generaciji konkretnih karaktera, odeće, pozadina...

Cilj projekta je primena LoRA metoda za ubacivanje novog koncepta u Stable Diffusion v1.5 model - npr. naučiti model da generiše karaktere u srpskoj nošnji.

## Skup podataka:
Prednost LoRA metoda, pored toga što model uči manji broj težina nego da menjamo sve težine modela, jeste ta što je za dotreniravanje relativno velikih diffusion modela (v1.5 ima skoro milijardu parametara) potreban relativno mali skup slika - oslanjamo se na ideju da očuvavamo znanje baznog modela.
S toga će se za treniranje koristiti samostalno prikupljen test skup koji će se ručno anotirati i proslediti na obuku - za obuku je potrebno proslediti sliku koja ilustruje koncept koji želimo da model nauči, kao i tekstualni opis ("prompt") za svaku fotografiju.

## Evaluacija:
Evaluacija ce biti vršena kroz pracenje performansi modela na validacionom i test skupu, kao i empirijski, kroz upoređivanje slika koje model generiše pre i posle dotreniravnja, kada se promptuje da generiše novi koncept koji smo probali da ga naučimo.

**Comment by njmarko** [comment]
Тема је одобрена.
Остави линк ка Github репозиторијуму пројекта.
Срећан рад!

**Comment by tince250** [comment]
https://github.com/tince250/sd-nosnja-lora-training
