### ISSUE TITLE
Sistem za detekciju košarkaške lopte i ažuriranje rezultata utakmice

### ISSUE THREAD

**Issue by jovannajdovski** [ftn-ai-lab/sc-2023#15]
## Tim:
- Jovan Najdovski, SV30/2020

## Asistent:
- Vidaković Dragan

## Definicija problema:
Razvoj sistema za detekciju objekata u stvarnom vremenu za automatsko praćenje košarkaške lopte tokom igre i detekciju prolaska lopte kroz koš, kako bi se automatski ažurirali poeni.

## Skup podataka:
Koristiće se više skupova podataka sa slikama košarkaških lopti i koševa. Skupovi će biti anotirani na Roboflow platformi (_bounding boxes, polygons, key points_).
Skupovi podataka imaju različite scenarije igre, različite svetlosne uslove i različite veličine košarkaške lopte.

## Metodologija:
Skup podataka će biti augmentovan i zatim treniran na YOLOv8 modelu. Razmatra se mogućnost Fine-tuning-a na već prethodno obučenom YOLOv8 modelu.

## Evaluacija:
Skupovi podataka bi bili kombinovani u jedan veći skup, potom na slučajan način podeljeni u podskupove od 80% za trening, 10% za test i 10% za validaciju.
 Za evaluaciju će se koristiti accuracy i precision metrike.

**Comment by vdragan1993** [comment]
Bilo bi dobro da konačan testni skup sadrži 20% podataka.

Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by jovannajdovski** [comment]
https://github.com/jovannajdovski/Basketball-Tracker
