### ISSUE TITLE
Prepoznavanje saobraćajnih znakova

### ISSUE THREAD

**Issue by branislavstojkovic70** [ftn-ai-lab/sc-2023#16]
#Naslov:
Prepoznavanje saobraćajnih znakova

## Tim:
- Branislav Stojković (SV64/2020)
- Asistent: Marko Njegomir

## Definicija Problema:
Cilj ovog projekta je razviti model dubokog učenja (CNN) za precizno prepoznavanje saobraćajnih znakova. Saobraćajni znakovi igraju ključnu ulogu u očuvanju bezbednosti saobraćaja, a razvoj autonomnih vozila i sistema za asistenciju vozaču zahteva pouzdano prepoznavanje ovih znakova kako bi vozila mogla da se pridržavaju saobraćajnih pravila. Projekat se fokusira na klasifikaciju saobraćajnih znakova u različite kategorije.

## Skup Podataka:
Za ovaj projekat koristićemo javno dostupan skup podataka sa Kaggle-a, nazvan "Traffic Signs Dataset". Ovaj skup podataka sadrži više od 50.000 slika različitih saobraćajnih znakova, koji su podeljeni u 43 različite klase. Skup podataka je podeljen na trening i test skupove, a ukupna veličina skupa podataka iznosi oko 300 MB. Slike su prikupljene u različitim uslovima osvetljenja i vremenskim uslovima, kako bi model bio robusan u realnim situacijama.

## Metodologija:
1. **Eksploracija skupa podataka:** Prvi korak projekta je istraživanje i analiza skupa podataka kako bismo bolje razumeli strukturu, distribuciju klasa i eventualne izazove u podacima.
2. **Izgradnja CNN modela:** Za ovaj projekat koristićemo konvolutivne neuronske mreže (CNN) za obradu slika. Model je Sequential i bice dizajniran tako da ima složenije konvolucione i potpuno povezane slojeve radi izdvajanja relevantnih karakteristika saobraćajnih znakova.
3. **Treniranje i validacija modela:** Nakon izgradnje modela, sprovodićemo trening na trening skupu podataka. Validacija će biti izvršena na posebnoj validacionoj grupi kako bismo pratili tačnost i gubitak modela tokom treninga. Parametri modela će se podešavati kako bismo postigli što bolje performanse.
4. **Testiranje modela sa test skupom:** Konačna evaluacija modela će se izvršiti korišćenjem odvojenog test skupa podataka. Testiranje će nam omogućiti da ocenimo kako se model ponaša na nepoznatim podacima.

## Evaluacija:
- Model će biti treniran na trening skupu podataka uz podelu od 80% trening i 20% validacija.
- Rezultati će biti detaljno analizirani kroz grafički prikaz tačnosti i gubitka tokom treninga i validacije. Očekujemo da će model postizati visoku tačnost na validacionom skupu.
- Performanse modela će biti dodatno evaluirane kroz metrike kao što su preciznost, odziv i F1 skor na test skupu podataka kako bismo razmotrili eventualne korake za poboljšanje performansi.

## Link do github-a
https://github.com/branislavstojkovic70/prepoznavanje-saobracajnih-znakova

**Comment by njmarko** [comment]
Који модел планираш да користиш за ово?
У евалуацији је потребно додати опис експерименталне поставке.

**Comment by njmarko** [comment]
Предлог прихваћен.
Остави линк до Github репозиторијума пројекта.
Срећан рад!

**Comment by branislavstojkovic70** [comment]
Hvala, postoji vec link na dnu specifikacije.
