### ISSUE TITLE
Korišćenje video snimaka šahovskih partija za obučavanje modela za igranje

### ISSUE THREAD

**Issue by NikolaSavic1709** [ftn-ai-lab/sc-2023#18]
### **Tim**
- SV 21/2020 Nikola Savić
- SV 33/2020 Jovan Šerbedžija

### **Asistent**
- Dragan Vidaković

## **Definicija problema**

- Projekat ima za cilj razvoj sistema dubokog učenja koji može analizirati video snimke šahovskih partija i prepoznati odigrane poteze, a zatim koristiti te informacije za učenje modela koji igra šah. 

### Skup podataka

- Skup podataka će se kreirati ručno, snimanjem šahovskih partija (sa [Chess.com](Chess.com))

### Metodologija
- Jedan video predstavlja jednu šahovsku partiju koja će biti podeljena na vremenske intervale koji predstavljaju poteze
- Pri svakom potezu, za detekciju početnog i krajnjeg polja figure će se koristiti Hough transformacija za detekciju ivica, kako bi se registrovala razlika između stanja table pre i posle poteza.
- Za identifikovanje tipa i boje figure koristiće se SVM klasifikator (<em>edit</em>) <em>kao i Sequential MLP Model klasifikator.</em>
- Izlaz iz obrade videa će biti skup poteza odigranih u toj šahovskoj partiji što će biti ulaz za treniranje (<em>edit</em>) <em>Feedforward</em> neuronske mreže koja će nakon treniranja biti u stanju da igra šah.  

### Evaluacija

- Evaluacija rezultata SVM klasifikatora i detekcije odigranog poteza će se meriti sledećim metrikama: tačnost, preciznost, odziv i f1 score
- Evaluacija rezultata rekurentne neuronske mreže će se meriti u odnosu na rezultate StockFish chess engine-a za istu poziciju.

**Comment by vdragan1993** [comment]
Pošto projekat rade dve osobe, pored SVM-a ubacite i jedan neuronski klasifikator za identifikovanje tipa i boje figure.

Koju eksperimentalnu postavku planirate da imate?

**Comment by NikolaSavic1709** [comment]
Za testiranje modela ćemo koristiti Cute chess biblioteku tako što će istrenirani model predstavljati i crnog i belog igrača.

**Comment by vdragan1993** [comment]
A koja eksperimentalna postavka će se koristiti za evaluaciju klasifikatora?

**Comment by NikolaSavic1709** [comment]
Za evaluaciju klasifikatora koristiće se podela skupa podataka na trening skup (80%) i test skup (20%) i meriće se navedenim metrikama

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by serbedzijajovan** [comment]
https://github.com/serbedzijajovan/ChessVisionAI
