### ISSUE TITLE
Softver za detekciju i čitanje zvaničnih identifikacionih dokumenata

### ISSUE THREAD

**Issue by JovanDozic** [ftn-ai-lab/sc-2023#19]
**Tim:** 
Jovan Dozic RA 75/2020

**Asistent:**
Filip Volarić

**Definicija problema:** 
Razviti softver za detekciju i čitanje zvaničnih identifikacionih dokumenata, kao što su lične karte, pasoši, i vozačke dozvole, iz bilo koje države. Softver treba da automatski prepozna tip dokumenta na osnovu slike, izvuče tekstualne podatke i klasifikuje ih.

**Motivacija:** 
Cilj je automatizovati proces prepoznavanja i ekstrakcije podataka iz identifikacionih dokumenata kako bi se poboljšala efikasnost u administrativnim procesima i poboljšala sigurnost.

**Skup podataka:** 
Koristiće se skup podataka sastavljen od digitalizovanih slika različitih identifikacionih dokumenata, prikupljenih uz poštovanje privatnosti i zakonskih regulativa. Podaci će biti podeljeni na trening skup (~70%), validacioni skup (~15%) i testni skup (~15%).

**Metodologija:** 
Primena konvolucijskih neuronskih mreža (CNN) za klasifikaciju dokumenata i optičko prepoznavanje karaktera (OCR) za ekstrakciju teksta. Korišćenje TensorFlow i Tesseract OCR alata. Implementiraće se krosvalidacija kako bi se smanjila pristrasnost i varijabilnost u proceni performansi modela.

**Evaluacija:**
Performanse sistema će se evaluirati kroz tačnost prepoznavanja tipa dokumenta i preciznost ekstrakcije teksta. Primarno će se koristiti metrike kao što su tačnost, preciznost i F1 skor. Dodatno, Levenshteinova udaljenost će se koristiti za procenu preciznosti ekstrakcije teksta, a Mean Average Precision (MAP) za ocenjivanje performansi klasifikacije dokumenata.

**Comment by Fickos** [comment]
- Neophodno je dodati opis eksperimentalne postavke. (podela trening/validacioni/test, krosvalidacija...)
- Možda bi za poređenje sa stvarnim sadržajem bilo bolje računati npr. Levenshtein, Mean Average Precision...

**Comment by JovanDozic** [comment]
Izvršena ispravka.

**Comment by Fickos** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
