### ISSUE TITLE
Merenje površine krova objekta korišćenjem R-CNN mreže

### ISSUE THREAD

**Issue by tamarailic** [ftn-ai-lab/sc-2023#2]
#### Tim:
Tamara Ilić, SV45/2020
Uroš Poček, SV57/202

#### Asistent:
Marko Njegomir

#### Definicija problema:
Detekcija i merenje površine krova objekta na osnovu satelitskih snimaka

#### Skup podataka:
Skup podataka sa satelitskim slikama dobijenih pomoću Google Maps API-ja. Trenutni skup je anotiran na Roboflow platformi, pomoću alata za označavanje segmenata od interesa. Skup će biti proširen prilikom izrade projekta.
https://universe.roboflow.com/solarise/roof-top-detection-8eyrx/browse?queryText=&pageSize=50&startingIndex=0&browseQuery=true

#### Metodologija:
Skup podataka će biti augmentovan i anotiran COCO anotacijom. Detectron 2 implementacija R50-FPN R-CNN mreže biće dodatno istrenirana da detektuje krovove na slici. Sama površina krova će se određivati na osnovu površine detektovane konture i pretvaranja piksela u metre kvadratne.

#### Evaluacija:
mPA i IOU

**Comment by njmarko** [comment]
У евалуацију је потребно додати опис експерименталне поставке.

**Comment by tamarailic** [comment]
Možete malo da mi pomognete šta se podrazumeva pod eksperimentalnu postavku? Ako se misli na način na koji će se testirati model, posaban deo skupa podataka odvojice se za testiranje.

**Comment by njmarko** [comment]
> Možete malo da mi pomognete šta se podrazumeva pod eksperimentalnu postavku? Ako se misli na način na koji će se testirati model, posaban deo skupa podataka odvojice se za testiranje.

Мислим баш на то што си навела (train/validation/test, crossvaliation...).

**Comment by njmarko** [comment]
Тема је одобрена.
Оставите линк до Github репозиторијума пројекта.
Срећан рад!

**Comment by tamarailic** [comment]
https://github.com/tamarailic/SolarPanelCalculation
