### ISSUE TITLE
Face Detection & Face Recognition

### ISSUE THREAD

**Issue by vukasinb7** [ftn-ai-lab/sc-2023#3]
# Face Detection & Face Recognition

## Definicija problema
Zadatak obuhvata prepoznavanje i detekciju lica unutar video strima, s ciljem olakšavanja mehanizma otključavanja pametne brave. Za streaming ce se koristiti ESP32-CAM uređaj. Link do repozitorijuma za pametnu bravu: https://github.com/vukasinb7/Smart-Lock. U sistemu postoji mogućnost dodavanja novih "sigurnih" lica kao i detekcija mraka u svrhu paljenja dodatnog svetla dok ne detektuje lice sa uspešnim ishodom ili do timeouta.

## Skup podataka
ImageNet dataset za ResNet50 pretreniran model sa ekstracijom feature za naša lica

## Metodologija
Prikupljanje i pretprocesiranje sadržaja skupa podatka u cilju izdvanja ključnih tačaka lica koji će biti ulazni podaci za odabrani model klasifikacije. Planirani model neuronske mreže za prepoznavanje lica koji će se koristiti je Resnet50 pretreniran model, a klasifirkator za detekciju lica će biti HaarCascade. 

## Evaluacija
Accuracy i precision metrika

## Tim
Jovan Jokić - SV47/2020,
Vukašin Bogdanović - SV9/2020,

## Asistent
Marko Njegomir

##Github Repository
https://github.com/vukasinb7/Smart-Lock

**Comment by njmarko** [comment]
У евалуацију је потребно додати опис експерименталне поставке.

**Comment by vukasinb7** [comment]
Olivetti skup lica će se podeliti na trening i validacioni skup u odnosu 80:20. Nakon toga će se model testirati nasumičnim odabirom para slika iz Olivetti skupa kao i nad ličnim skupom podatak.

**Comment by njmarko** [comment]
У евалуацију додајте још и recall и Ф1 меру.

Код оваквог система је корисно корисно изразити и False Acceptance Rate (FAR. У матрици конфузије се зове још и False Positive Rate. Рачуна се као 1 - recall) и False Rejection Rate (FRR. У матрици конфузије се зове још и False Negative Rate). Они дају информацију колико често ће неауторизована особа добити приступ, и колико често ће ауторизована особа бити одбијена.

Пројекат одобрен.
Потребно је да окачите линк до Github репозиторијума пројекта.
Срећан рад!
