### ISSUE TITLE
Детекција корова у пољопривредним усевима

### ISSUE THREAD

**Issue by magley** [ftn-ai-lab/sc-2023#4]
### Тим
Лазар Магазин SV 25/2020

### Асистент
Марко Његомир

### Дефиниција проблема
Истренирати интелигентни модел да детектује биљке са фотографије и класификује их на основу тога да ли је у питању нежељен коров или усев.

Улаз је фотографија дела парцела, а излаз је списак детектованих објеката и њима придружене класе и њихови bounding box-ови.

### Мотивација проблма
Међу највећим проблемима у пољопривреди истичу се корови.

Студија случаја: пшеница. Као друга најзаступљенија култура биљне производње у Србији са уделом од 24,3% обрадивог земљишта у 2022. години [[1]](https://media.srbija.gov.rs/medsrp/dokumenti/ZK-2022-I-knjiga041022.pdf), пшеница и њени корови представљају актуелну тему у развоју интензивног типа пољопривреде. Само у Србији забележено је преко 200 коровских врста које штете пшеници.

Узроци настанка корова су: [[2]](https://aspace.agrif.bg.ac.rs/bitstream/id/2809/4260.pdf)
- гајење монокултурних поља
- употреба семена запрљаног семенима корова
- низак квалитет земљишта
- неодговарајуће величине парцела
- лоше ђубриво.

Сузбијање ових корова је неопходно како би се заштитио квалитет усева, максимизовао приход, очувао квалитет земљишта итд. Неке од техника за сузбијање корова су:
- гајење плодореда уместо монокултуре
- употреба квалитетнијег семена
- **уклањање корова**

Применом рачунарске визије, машине попут роботских руку, дронова итд. биле би у стању да препознају коров и уклоне га чупањем или прскањем хербицидима. Поред овога, пољопривредници би релативно брзо добили увид у стање парцела приликом експериментисања са различитим ђубривом, семењем, техникама обраде земљишта итд.
Примери реалне употребе рачунарске визије за решавање овог проблема: [[3]](https://www.linkedin.com/pulse/automated-weed-detection-ai-enhanced-solution-control-neil-sahota-1k3wf/), [[4]](https://www.tomorrowsworldtoday.com/agriculture-and-food/new-ai-robot-can-help-farmers-remove-weeds-from-fields/), [[5]](https://github.com/Weed-AI/Weed-AI).

### Скуп података
Користиће се [неки](https://www.kaggle.com/datasets/ravirajsinh45/crop-and-weed-detection-data-with-bounding-boxes/data) [од следећих](https://www.kaggle.com/datasets/imsparsh/deepweeds) скупова података. У питању су фотографије усева и корова, фотографисаних релативно близу у односу на камеру. На фотографији се може појавити ниједан или више објеката од значаја.

По потреби ће се слике додадно анотирати користећи RoboFlow радни овкир.

### Методологија

Основа за модел је конволутивна неуронска мрежа [Yolo v8](https://github.com/ultralytics/ultralytics), претренирана на [COCO скупу података](https://cocodataset.org/#home).

_Fine tuning_-ом ће се модел доучити на споменутим сликама. Скуп података ће се поделити на тренинг, тест и валидациони скуп (вероватно у односу 60:20:20).

### Евалуација

Посматраће се прецизност, одзив, _F1_ мера, _average precision_, _mean average precision_, _box loss_, _intersection over union_ и _class loss_. Такође ће се узети у обзир и брзина евалуације појединачних слика, у циљу оптимизације за благовремену детекцију.

### Репозиторијум

[Репо](https://github.com/magley/iSeeWeeds)

**Comment by njmarko** [comment]
Свака част на детаљном истраживању и опису мотивације проблема! 

Ако будеш имао довољно података, мислим да ћеш моћи да повећаш удео тог тренинг скупа.

За детекцију објеката се најчешће рачунају AP (average precision) и mAP (mean average precision), па би требало и њих додати. Пошто радиш класификацију, а имаш и прецизност и одзив, можеш израчунати и Ф1 меру која је хармонијска средина прецизности и одзива.

За bounding box евалуацију се треба додати и IoU (intersection over union).

Пројекат је одобрен.
Потребно је да оставиш линк ка Github репозиторијуму пројекта.
Срећан рад!
