### ISSUE TITLE
Detekcija pravilnog izvođenja vežbi

### ISSUE THREAD

**Issue by KristinaPopovSV5-2020** [ftn-ai-lab/sc-2023#5]
Detekcija pravilnog izvođenja vežbi
==
**Tim**
- Kristina Popov SV5/2020
- Zorica Pešić SV50/2020

**Asistent**
 Dragan Vidaković

**Definicija problema**
Detekcija položaja tela čoveka kako bi izbrojali koliko puta je uradio prepoznatu vežbu, s tim da će brojati samo ukoliko pravilno uradi vežbu. Cilj je  motivisanje korisnika kroz prikaz broja pravilnih vežbi kako bi ih podstakli na održavanje tačnosti u izvođenju.

**Skup podataka**
Lični skup  videa.

**Metodologija**
Za prepoznavanje vežbi koristićemo YOLOv4, a  MediaPipe za detekciju ključnih tačaka na telu, radi utvrđivanja ispravnosti izvođenja vežbi. Za klasifikaciju SVM klasifikator.

**Evaluacija**
Accuracy, precision, recall, f1

**Comment by vdragan1993** [comment]
U definiciji problema je neophodno navesti koje sve vežbe će se prepoznavati.
U evaluaciji je neophodno dodati opis eksperimentalne postavke.
Pošto projekat rade dve osobe, u metodologiji je neophodno dodati i neki neuronski klasifikator pored SVM-a.

**Comment by KristinaPopovSV5-2020** [comment]
Mislile smo da imamo 4 vrste vežbi: čučnjevi, sklekovi, trbušnjaci i star jumps. Skup podataka se sastoji od videa koji demonstriraju pravilno ili nepravilno rađenje vežbi. U videima ćemo pomoću Mediapipe pronalaziti pozicije ključnih 33 tačaka u telu na osnovu kojih ćemo proveravati ispravost vežbe.  Pored SVM klasifikatora  koristićemo i  TensorFlow neuronski klasifikator.

**Comment by vdragan1993** [comment]
Koju eksperimentalnu postavku planirate da imate? Da li će to biti podela skupa podataka na trening/validacioni/test, krosvalidacija ili nešto treće?

**Comment by KristinaPopovSV5-2020** [comment]
Skup podataka će biti podeljen na trening i test podatke (80:20).

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by KristinaPopovSV5-2020** [comment]
Link ka GitHub repozitorijumu https://github.com/KristinaPopovSV5-2020/Fitness-Movement-Detection, hvala.
