### ISSUE TITLE
Face and Voice Recognition for Authentication purpose

### ISSUE THREAD

**Issue by janosevicsm** [ftn-ai-lab/sc-2023#6]
# Face and Voice Recognition for Authentication purpose
## Definicija problema
Projekat ima za cilj razvoj sistema za autentifikaciju putem detekcije lica i prepoznavanje glasa. Koristiće se tehnike dubokog učenja, kako bi se omogućilo pouzdano prepoznavanje lica i glasa korisnika. Ovaj sistem bi bio pogodan za integraciju u različite aplikacije kao sredstvo za bezbednu autentifikaciju.
## Motivacija problema
Rešavanje ovog problema ima praktičnu primenu u domenu sigurnosti i korisničkog iskustva. Softver za detekciju lica i glasa može se primeniti u raznim oblastima, uključujući pristup aplikacijama, sigurnosne sisteme, ili čak finansijske transakcije, pružajući dodatne slojeve sigurnosti uz istovremeno poboljšanje korisničke interakcije.
### Preprocesiranje podataka:
Implementacija algoritama za preprocesiranje slika radi poboljšanja kvaliteta podataka, normalizacije osvetljenja i eliminacije šuma koji mogu uticati na detekciju.
### Detekcija lica i zvuka:
Upotreba prethodno treniranih modela za detekciju lica i zvuka.
### Ekstrakcija karakteristika lica:
Primena neuronskih mreža za ekstrakciju karakteristika iz detektovanih regija koje sadrže lica.
## Evaluacija
Tačnost detekcije lica i zvuka:
Izračunavanje tačnosti sistema u prepoznavanju lica i zvuka na testnom skupu podataka.
## Tim
- Miloš Čuturić - SV11/2020
- Marko Janošević - SV46/2020
## Asistent
- Marko Njegomir

**Comment by njmarko** [comment]
Које моделе планирате да користите?

**Comment by janosevicsm** [comment]
Planiramo da probamo više modela tokom razvoja, da bismo videli koji su najbolji za naš konkretan problem, pa ćemo naknadno dopuniti specifikaciju, da ne bismo unapred izabrali pogrešan, ako je to dopustivo.

**Comment by janosevicsm** [comment]
> Које моделе планирате да користите?

Planiramo da probamo više modela tokom razvoja, da bismo videli koji su najbolji za naš konkretan problem, pa ćemo naknadno dopuniti specifikaciju, da ne bismo unapred izabrali pogrešan, ako je to dopustivo.

**Comment by njmarko** [comment]
Дозвољено је да промените модел у току рада јер се може десити да просто неки приступ који сте замислили не ради када кренете да имплементирате решење.

Занима ме само које моделе за сада разматрате?

**Comment by janosevicsm** [comment]
> Дозвољено је да промените модел у току рада јер се може десити да просто неки приступ који сте замислили не ради када кренете да имплементирате решење.
> 
> 
> 
> Занима ме само које моделе за сада разматрате? 

Za detekciju lica: MTCNN, RetinaFace, BlazeFace.
Za detekciju zvuka: VGGish, OpenL3, DeepSBD.

**Comment by njmarko** [comment]
Пошто сте ставили да ћете евалуирати на тестном скупу, претпостављам да вам је онда експеримантална поставка train/val/test скуп. 
У евалуацију додајте још и precision, recall и Ф1 меру.

Код оваквог система је корисно корисно изразити и False Acceptance Rate (FAR. У матрици конфузије се зове још и False Positive Rate. Рачуна се као 1 - recall) и False Rejection Rate (FRR. У матрици конфузије се зове још и False Negative Rate). Они дају информацију колико често ће неауторизована особа добити приступ, и колико често ће ауторизована особа бити одбијена.

Пројекат одобрен.
Потребно је да окачите линк до Github репозиторијума пројекта.
Срећан рад!
