### ISSUE TITLE
Audio prevodilac: Transformacija srpskog jezika u druge svetske jezike

### ISSUE THREAD

**Issue by JelenaMikovic** [ftn-ai-lab/sc-2023#8]
**Tim:**

- SV42/2020 Babić Danilo
- SV49/2020 Erdelji Marko
- SV61/2020 Miković Jelena

**Asistent:**

- Njegomir Marko
- Vidaković Dragan

**Definicija problema:**
- U današnjem globalizovanom društvu postoji potreba za audio prevodom sa srpskog na druge jezike.  Efikasna rešenja u oblasti audio prevoda omogućavaju autentičnu međunarodnu komunikaciju i pristup kulturnim sadržajima na srpskom jeziku.

**Skup podataka:**
- Audio recognition: https://huggingface.co/datasets/google/fleurs/viewer/sr_rs

**Metodologija:**
- Iz skupa podataka vršićemo filtriranje i obradu audio i tekstualnih materijala na srpskom jeziku. Specifično, razvijaćemo model za translaciju audio zapisa u tekstualni format, a obuka će se sprovoditi na relevantnim podacima. Generisani tekst će zatim biti preveden na ciljni jezik (engleski). Konačno, prevedeni tekst će se transformisati u audio format putem prethodno treniranog i optimizovanog modela za tekst u govor (text-to-speech). 

**Evaluacija:**
- Metrike poput WER (Word Error Rate) za performanse

**Comment by vdragan1993** [comment]
Koje modele planirate da koristite/razvijate?
Kakva će biti eksperimentalna postavka?

**Comment by MarkoErdelji** [comment]
Modeli:
Za prevodjenje: https://huggingface.co/facebook/nllb-200-distilled-1.3B
Za tts: https://huggingface.co/facebook/mms-tts-eng
Za audio to text:Razvijamo nas RNN model sa datim datasetom,osobine zvuka ćemo izdvojiti koristeći MFCC 

Eksperimentalna postavka se sastoji od toga da nam je dataset već podeljen na podatke za trening,validaciju i test.

**Comment by vdragan1993** [comment]
Da li ćete modele za prevođenje i tts samo primeniti, ili ćete raditi neki fine-tuning/transfer learning?

**Comment by MarkoErdelji** [comment]
Radićemo fine-tuning ovih modela za naš konkretan slučaj.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by MarkoErdelji** [comment]
https://github.com/Danilo-Babic/AudioTranslator-RS-EN
