### ISSUE TITLE
Kontrolisanje video igre koristeći "hand gestures"

### ISSUE THREAD

**Issue by bmijanovic** [ftn-ai-lab/sc-2023#9]
### 1. Tim

Članovi tima:

- Bojan Mijanović, SV8/2020
- Ognjen Radovanović, SV74/2020

### 2. Asistent

Marko Njegomir

### 3. Definicija Problema

Razviti sistem za kontrolu video igre pomoću kamere i detekcije šake, omogućavajući igračima da upravljaju igrom kroz jednostavne gestove i pokrete šake umesto klasičnih kontrolera.

### 4. Motivacija Problema

Cilj nam je unaprediti iskustvo igranja video igara, čineći ga pristupačnijim i zabavnijim.

### 5. Skup Podataka

Za treniranje modela bismo koristili već postojeći data set.
https://www.kaggle.com/datasets/gti-upm/leapgestrecog

### 6. Metodologija

Koristićemo tehniku dubokog učenja. Napisali bismo našu verziju YOLO algoritma.

### 7. Evaluacija

Evaluacija će se sprovoditi kroz:
Performanse Kontrole Igre: Testiranje efikasnosti sistema u upravljanju igrom pomoću detektovanih gestova.

**Comment by njmarko** [comment]
Како планирате да евалуирате ваш YOLO модел на том скупу података (експериментални поступак)?
Које мере перформанси ћете користити за евалуацију YOLO модела на том скупу?

**Comment by bmijanovic** [comment]
Podelili bismo skup podataka na 70% za treniranje, 15% za validaciju i 15% za testiranje našeg modela. Mere performansi za evaluaciju modela bismo koristili Precision, Recall i F1 score, a na kraju i evaluaciju funkcionisanja samog sistema kroz tačnost akcija koje su izvršene.

**Comment by njmarko** [comment]
Пројекат одобрен.
Оставите линк до Github репозиторијума пројекта.
Срећан рад.

**Comment by bmijanovic** [comment]
https://github.com/bmijanovic/hand-gesture-controller
